In [1]:
# Dependencies
import pandas as pd
from citipy import citipy
from pandas import DataFrame

In [2]:
# Store filepath in a variable
Housing_data = "cleaned_housing_data.csv"

In [3]:
# Read our Data file with the pandas library
# Not every CSV requires an encoding, but be aware this can come up
Housing_data_df = pd.read_csv(Housing_data)

In [4]:
# Show just the header
Housing_data_df.head()

,state,counties,city,price,type,beds,baths,sqfeet,latlong
0,ca,sacramento,roseville,1900,apartment,3,2.0,1250,"(38.7724, -121.263)"
1,ca,sacramento,rosemont,1325,apartment,1,1.0,640,"(38.5643, -121.378)"
2,ca,sacramento,florin,2010,apartment,3,2.0,1232,"(38.4249, -121.471)"
3,ca,sacramento,manteca,2699,house,4,3.5,2660,"(37.7661, -121.201)"
4,ca,sacramento,folsom,1450,apartment,1,1.0,700,"(38.6709, -121.153)"

In [12]:
# Renaming the headers to be consistent with crime_data.csv
Renamed_Housing_data_df = Housing_data_df.rename(columns={"city": "Sac County City","price": "Monthly price($)"})
Renamed_Housing_data_df

,state,counties,Sac County City,Monthly price($),type,beds,baths,sqfeet,latlong
0,ca,sacramento,roseville,1900,apartment,3,2.0,1250,"(38.7724, -121.263)"
1,ca,sacramento,rosemont,1325,apartment,1,1.0,640,"(38.5643, -121.378)"
2,ca,sacramento,florin,2010,apartment,3,2.0,1232,"(38.4249, -121.471)"
3,ca,sacramento,manteca,2699,house,4,3.5,2660,"(37.7661, -121.201)"
4,ca,sacramento,folsom,1450,apartment,1,1.0,700,"(38.6709, -121.153)"
...,...,...,...,...,...,...,...,...,...
2380,ca,sacramento,west sacramento,1625,apartment,1,1.0,735,"(38.4962, -121.53)"
2381,ca,sacramento,rancho cordova,1100,apartment,1,1.0,620,"(38.5934, -121.318)"
2382,ca,sacramento,florin,1300,apartment,2,1.0,808,"(38.4743, -121.445)"
2383,ca,sacramento,lincoln,2595,house,4,3.0,2370,"(38.9025, -121.32)"
2384,ca,sacramento,fair oaks,1150,apartment,2,1.0,850,"(38.6448, -121.268)"

In [39]:
# Filtering to get the cities in sacramento consistent with data in crime_data excel sheet
Sacramento_Housing_df = Renamed_Housing_data_df.loc[Renamed_Housing_data_df["Sac County City"].isin(["sacramento","citrus heights","elk grove","folsom","galt","rancho cordova"])]
#Sacramento_Housing_df

# sorting by first name 
#Sacramento_Housing_df.sort_values("Sac County City", inplace = True) 

#df.sort_values('C', ascending=False).drop_duplicates(subset=['A', 'B'],inplace = True)

#df.sort_values('C', ascending=False).drop_duplicates(subset=['A', 'B'])

# Remove duplicate rows 
Sacramento_Housing_df.drop_duplicates(subset =["Sac County City","Monthly price($)","beds","baths","sqfeet","latlong"],inplace = True)
Sacramento_Housing_df

C:\Users\yekhi\anaconda3\envs\PythonDataViz\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  del sys.path[0]

,state,counties,Sac County City,Monthly price($),type,beds,baths,sqfeet,latlong
4,ca,sacramento,folsom,1450,apartment,1,1.0,700,"(38.6709, -121.153)"
5,ca,sacramento,sacramento,1211,apartment,1,1.0,632,"(38.6131, -121.506)"
6,ca,sacramento,citrus heights,1250,apartment,1,1.0,710,"(38.6946, -121.269)"
8,ca,sacramento,citrus heights,1199,apartment,1,1.0,640,"(38.7113, -121.272)"
11,ca,sacramento,rancho cordova,1177,apartment,1,1.0,704,"(38.5786, -121.295)"
...,...,...,...,...,...,...,...,...,...
2325,ca,sacramento,sacramento,1495,house,2,1.0,832,"(38.6157, -121.505)"
2346,ca,sacramento,sacramento,1695,apartment,1,1.0,700,"(38.5817, -121.485)"
2351,ca,sacramento,sacramento,1350,apartment,0,1.0,475,"(38.5813, -121.484)"
2352,ca,sacramento,rancho cordova,2795,house,5,3.0,2584,"(38.5802, -121.274)"
2370,ca,sacramento,sacramento,2320,apartment,2,2.0,1148,"(38.5628, -121.468)"

In [7]:

#[Housing_relevant_columns_df["Sac County City"] == "Citrus Heights", :]
#Sacramento_city_df.head(5)

#df_final = df_final[["state", "city","counties", "price","type", "beds", "baths", "sqfeet", "latlong"]]
#columns_df = Housing_data_df.columns
#columns_df# Relevant Housing data set columns
#Housing_relevant_columns_df = Housing_data_df[["state", "region", "price","type", "beds", "baths", "sqfeet", "lat", "long"]]
#Housing_relevant_columns_df.head()